set nocompatible " We’re running Vim, not Vi!
execute pathogen#infect()

syntax on " Enable syntax highlighting
color dracula
set incsearch " incremental search
set ignorecase " case insensitive
set hlsearch " highlight search result

" Make vim indent 2 spaces for ruby files only
filetype plugin indent on
set sw=4
set ts=4
:autocmd Filetype ruby set softtabstop=2
:autocmd Filetype ruby set sw=2
:autocmd Filetype ruby set ts=2

filetype on " Enable filetype detection
filetype indent on " Enable filetype-specific indenting
filetype plugin on " Enable filetype-specific plugins

" Set line numbering, shift width
set number
set expandtab
set shiftwidth=2
set cursorline
set hidden

" yank from clipboard
set clipboard+=unnamedplus

" map ;; to Esc
:imap ;; <Esc>
:vmap ;; <Esc>

" set leader key
let mapleader=","

" copy the entire file
nmap <leader>c ggVGy
" add binding.pry in normal mode
nnoremap <leader>b obinding.pry<esc>

" when pressing 0, go to the the first text in the line
nmap 0 ^
" enter gives a new line when in command mode without entering insert mode
nmap <CR> o<Esc>
" Ctrl + e to jump out of closing parenthese/brackets/quotation marks in
" insert mode
inoremap <C-e> <C-o>A
" set x not go into the default registry
nnoremap x "_x
