set nocompatible " We’re running Vim, not Vi!
execute pathogen#infect()

" yank from clipboard
set clipboard=unnamed

syntax on " Enable syntax highlighting
color dracula
set incsearch " incremental search
set ignorecase " case insensitive
set hlsearch " highlight search result

" Make vim indent 2 spaces for ruby files only
filetype plugin indent on
set sw=4
set ts=4
:autocmd Filetype ruby set softtabstop=2
:autocmd Filetype ruby set sw=2
:autocmd Filetype ruby set ts=2

filetype on " Enable filetype detection
filetype indent on " Enable filetype-specific indenting
filetype plugin on " Enable filetype-specific plugins

" Set line numbering, shift width
set number
set expandtab
set shiftwidth=2
set cursorline

" map ;; to Esc
:imap ;; <Esc>
